Ejercicio 1

Crea una array de numpy con los siguiente números primos: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29

- Muestra el último elemento. Y debes hacerlo sin saber su longitud.
- Muestra el 3º elemento
- Muestra el último y 3º elemento.
- Muestra del 2º al 5º elemento.
- Muestra el 2° y el 5° elemento
- Muestra el último y el penúltimo elemento. Y debes hacerlo sin saber su longitud.


In [1]:
import numpy as np

primos = np.array([2,3,5,7,11,13,17,19,23,29])
segundo_elemento = primos[1]
tercero_lista = primos[2]
quinto_lista = primos[4]
penultimo_lista = primos[-2]
ultimo_lista = primos[-1]
print(f"Ultimo elemento {ultimo_lista}")
print(f"3º elemento {tercero_lista}")
print(f"Último elemento es {ultimo_lista} y 3º elemento es {tercero_lista}")
print(f"2º elemento es {segundo_elemento} y 5º elemento es {quinto_lista}")
print(f"Ultimo elemento es {ultimo_lista} y penultimo es {ultimo_lista}")

Ultimo elemento 29
3º elemento 5
Último elemento es 29 y 3º elemento es 5
2º elemento es 3 y 5º elemento es 11
Ultimo elemento es 29 y penultimo es 29


Ejercicio 2 
Crea una array de numpy con los siguiente números primos: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29 pero que el array sea de tipo "float" de 32 bits.
- Usando la función arange de numpy crea un array con los números del 100 al 200 pero sin incluir el 200. Muestra el resultado.
- Usando la función range estándar de Python crea un array con los números del 100 al 200 pero sin incluir el 200. Muestra el resultado. ¿Qué diferencia hay con arange?


In [2]:
primos = np.array([2,3,5,7,11,13,17,19,23,29])
primos32 = np.array(primos, dtype=np.float32)
print(primos32)

lista_numeros = np.arange(100,200)
print(lista_numeros)

print(list(range(100,200)))

# La diferencia es la coma. Uno es list de np

[ 2.  3.  5.  7. 11. 13. 17. 19. 23. 29.]
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]
[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199]


Ejercicio 3
Crea la siguiente matriz:

- Muestra el elemento de la fila 2º y la columna 3º. Es el valor del 7.
- Muestra la 3º Fila
- Muestra la 2º Columna
- Muestra la 2º y 3º Columna
- Muestra la 2º y 3º Fila
- Muestra la última columna. Debe funcionar independientemente del número de columnas.
- Muestra la 2º y 4º Columna y la 1º y 3º fila
- Muestra de la 2º a la 3º Columna y de la 1º a la 3º fila
- Muestra todas las columnas excepto la primera y la última. Debe funcionar independientemente del número de columnas.
- Muestra todas las filas excepto la primera y la última. Debe funcionar independientemente del número de filas.
- Muestra todas las columnas excepto la primera y la última y todas las filas excepto la primera y la última. Debe funcionar independientemente del número de filas y columnas.
- Imprime la matriz y haz que las cabeceras de cada columna sean A, B , C y D


In [46]:
matriz = np.array([[1,4,6,5],[4,1,7,3],[2,9,1,2],[6,3,1,1]])
segundaFilaTerceraColumna = matriz[1][2]
terceraFila = matriz[2]
segundaColumna = matriz[:,1:2]
segundaYterceraColumna = matriz[:,1:3]
segundaYterceraFila = matriz[1:3,:]
ultimaCol = matriz[:,-1:]
segundaYcuartaColYprimeraYterceraFila = matriz[0:3,1:4]
segundaYterceraColYprimeraYterceraFila = matriz[0:3,1:3]
NoPrimeraUltima = matriz[:,1:-1]
NoPrimeraUltimaFC = matriz[1:-1,1:-1]

print(f"Muestra el elemento de la fila 2º y la columna 3º. Es el valor del 7. Valor: {segundaFilaTerceraColumna}")
print(f"Muestra la 3º Fila {terceraFila}")
print(f"Muestra la 2º Columna \n{segundaColumna}")
print(f"Muestra la 2º y 3º Columna \n{segundaYterceraColumna}")
print(f"Muestra la 2º y 3º Fila \n{segundaYterceraFila}")
print(f"Muestra la ultima Columna \n{ultimaCol}")
print(f"Muestra la segunda Y cuarta Col Y primera Y terceraFila \n{segundaYcuartaColYprimeraYterceraFila}")
print(f"Muestra la segunda Y tercera Col Y primera Y terceraFila \n{segundaYterceraColYprimeraYterceraFila}")
print(f"Muestra todas menos primera y ultima columnas \n{NoPrimeraUltima}")
print(f"Muestra todas menos primera y ultima columnas y columnas \n{NoPrimeraUltimaFC}")
print(f" A B C D")
for i in matriz:
    print(i)



Muestra el elemento de la fila 2º y la columna 3º. Es el valor del 7. Valor: 7
Muestra la 3º Fila [2 9 1 2]
Muestra la 2º Columna 
[[4]
 [1]
 [9]
 [3]]
Muestra la 2º y 3º Columna 
[[4 6]
 [1 7]
 [9 1]
 [3 1]]
Muestra la 2º y 3º Fila 
[[4 1 7 3]
 [2 9 1 2]]
Muestra la ultima Columna 
[[5]
 [3]
 [2]
 [1]]
Muestra la segunda Y cuarta Col Y primera Y terceraFila 
[[4 6 5]
 [1 7 3]
 [9 1 2]]
Muestra la segunda Y tercera Col Y primera Y terceraFila 
[[4 6]
 [1 7]
 [9 1]]
Muestra todas menos primera y ultima columnas 
[[4 6]
 [1 7]
 [9 1]
 [3 1]]
Muestra todas menos primera y ultima columnas y columnas 
[[1 7]
 [9 1]]
 A B C D
[1 4 6 5]
[4 1 7 3]
[2 9 1 2]
[6 3 1 1]



Ejercicio 4
El siguiente array contiene las temperaturas medias que ha hecho en Valencia en cada mes [10.2, 10.7, 13.3, 15.8, 19.3, 23.6, 26, 25.9, 22.8, 19.1, 13.9, 10.8 ]
- Muestra las temperaturas cuyo valor sea mayor que 20
- Muestra las temperaturas cuyo valor sea menor que 11
- Muestra las temperaturas cuyo valor sea mayor que 20 o menor que 11


In [53]:
array = np.array([10.2, 10.7, 13.3, 15.8, 19.3, 23.6, 26, 25.9, 22.8, 19.1, 13.9, 10.8 ])
print(f"Muestra las temperaturas cuyo valor sea mayor que 20 {array[array>20]}")
print(f"Muestra las temperaturas cuyo valor sea menor que 11 {array[array<11]}")
print(f"Muestra las temperaturas cuyo valor sea mayor que 20 o menor que 11 {array[(array<11) | (array>20)]}")

Muestra las temperaturas cuyo valor sea mayor que 20 [23.6 26.  25.9 22.8]
Muestra las temperaturas cuyo valor sea menor que 11 [10.2 10.7 10.8]
Muestra las temperaturas cuyo valor sea mayor que 20 o menor que 11 [10.2 10.7 23.6 26.  25.9 22.8 10.8]


Ejercicio 5
Carga los datos de un dataset muy utilizado en la ciencia de datos con con el siguiente código:
from sklearn.datasets import load_iris
datos=load_iris().data
resultado=load_iris().target


- Crea un array llamado sepal_length con las 99 primeras filas y la 1º columna de la matriz datos
- Crea un array llamado petal_length con las 99 primeras filas y la 3º columna de la matriz datos
- Crea un array llamado x juntando las 2 columnas sepal_length y petal_length
- Crea un array llamado y con las 99 primeras filas del vector resultado
- Crea un array llamado x con las 99 primeras filas , la 1º columna y la 3º columna de la matriz datos.


In [74]:
from sklearn.datasets import load_iris
datos=load_iris().data
resultado=load_iris().target
sepal_length = datos[0:100,0:1]
petal_length = datos[0:100,2:3]
x = np.hstack((sepal_length, petal_length))
y = resultado[:100]

# print(datos)
# print(sepal_length)
# print(petal_length)
# print(x)

# print(resultado)
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
